### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by Theluga** [SecUSo/privacy-friendly-notes#125]
I only discovered PFA today, I'm so happy for this movement against tracking and "legal" spyware. 

I would like to suggest the ability to change themes or include a night mode to the app. 

I am very happy with this app as a simple note replacement. Thank you very much!

**Comment by coderPaddyS** [comment]
Thank you Theluga for your kind words. We already have an issue open to add a dark mode to the app, see #86. I'm going to close this issue for now.
