### ISSUE TITLE
with very large notes everything lags, fix it

### ISSUE THREAD

**Issue by Wjxfi** [SecUSo/privacy-friendly-notes#134]

**Comment by coderPaddyS** [comment]
Thank you for your request. However it would be nicer if you could 

  a) give us more information on your problem, 
  b) describe ways to reproduce the problem
  c) not demand us to fix.

I've tried a text note containing 256 chapters of Lorem Ipsum on my device and did not notice any lag whatsoever.
Please provide more information on your problem.
