### ISSUE TITLE
leaked window android.widget.PopupWindow when create audio notes 

### ISSUE THREAD

**Issue by RiShinku** [SecUSo/privacy-friendly-notes#139]
Click the add icon in the main activity, choose audio notes, and my logcat monitored that 'android.view.WindowLeaked: Activity org.secuso.privacyfriendlynotes.ui.AudioNoteActivity has leaked window android.widget.PopupWindow'

**Comment by RiShinku** [comment]
When access to the main activity, some other errors caught:
'Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"'
'Fail to acquire dataAnalyzerService...'
'AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@fb676cd'
'parse speed value length error'
these errors seem to be something to do with the compatibility.

**Comment by coderPaddyS** [comment]
On which Android version are you? What version of adb and Android Studio do you use? Whats the exact output given by logcat?
This doesn't occur on my devices
