### ISSUE TITLE
[Bug] Export not working

### ISSUE THREAD

**Issue by udenr** [SecUSo/privacy-friendly-notes#154]
When I try to export a note on Android 13 or 14 (API 33/34), I get the message ``Permission to write to external storage is required for this function``.
The app should request permission instead of giving an error message.

**Comment by hoolgascht** [comment]
Same here on samsung galaxy A53 with Android 14. App gives error msg which is crippled and manual adding permission via settings is not possible. Bitte Fehler beheben, so ist die App kein Ersatz für mich auf der Suche nach Alternativen für die Simple mobile Tools ...
