### ISSUE TITLE
Export reminders too

### ISSUE THREAD

**Issue by licaon-kter** [SecUSo/privacy-friendly-notes#28]

**Comment by Yonjuni** [comment]
Is this regarding the sharing function?

**Comment by licaon-kter** [comment]
Yes, and also the save function.

**Comment by Yonjuni** [comment]
Belongs together https://github.com/SecUSo/privacy-friendly-notes/issues/28

**Comment by licaon-kter** [comment]
Umm?

**Comment by notfoss** [comment]
@licaon-kter, what Yonjuni means is that this issue should be handled with issue #33.

**Comment by Kamuno** [comment]
Duplicate of #33

**Comment by T-vK** [comment]
See #94
