### ISSUE TITLE
differences between save icon and save button unclear

### ISSUE THREAD

**Issue by treaki** [SecUSo/privacy-friendly-notes#35]
Hi,

your app is a good one for the first release but the usability, user experience it is still a bit rough:

first of all your app is starting with a splash screen but i dont think that is nessesery do do that if you write it efficiently. The Notepad app[01] i was using until i have android and i can remember comes good out without any useless splash screen.

Secondly and much more important is that if i am editing with your app a note there is once a floppy icon (save icon) at the top action bar without any text and secoundly a button with the word save on at the button (translating that roughly from my german user interface so maybe they are called differently). As a normal user i would think both would do the same, save the note. But it is on the contrary, these floppy icon means export this note to the sdcard. Thats not a good look and feel, its not what the user expect. So i would suggest moving that export option from the unclear symbol at the top into the menu (⋮) as a text "export" (or at least a better symbol).

also i dont understand why i have (as a dumb user not as someone who nows something about menaging datastructures) to save a note and open it up again if i want to set a reminder to it. Why cant i just set a reminder the first time when i have just created that note.

i hope youll fix that

thanks

ps: you may should that export just move into the settings menu completely with the possibility to export all, import them back for backup purposes to the sdcard

Annotations:
01: Notepad (Basic note taking) - https://f-droid.org/app/bander.notepad

**Comment by licaon-kter** [comment]
#25 and #33 ;)

**Comment by Yonjuni** [comment]
Thanks for your comments.

1) Splash Screen
The Splash Screen does not take up any resources and if there would not be a splash screen the screen would be white. Depending in the device's CPU the splash will be displayed, longer shorter or not at all. So we use it as a common design element, that the user does not have to see a white screen and we want all devices to have an equal design. 

2) I understand the confusion and we will discuss this in our group I have moved it to to close this one (https://github.com/SecUSo/privacy-friendly-notes/issues/36)

3) See https://github.com/SecUSo/privacy-friendly-notes/issues/25

4) We are currently developing another possibility to import/export/sync and share the content of all our apps. So your suggestion would of course work but be work around for our other solution, thus we will not change it, but there will be possibilities to export all notes at once. You can follow this functionality here. https://github.com/SecUSo/privacy-friendly-notes/issues/33

**Comment by treaki** [comment]
thanks for your detailed replyes folks, i understand your point 2 to 4 @Yonjuni but i still think there is something done that needs to much power on the initial start up of the app because if i compare https://f-droid.org/app/bander.notepad and yours on a freshly booted system bander's comes up instantly but yours are showing the splash for quite a notable time. Maybe you have to improve the startup time somewhere else, i dont know the code, but imho its to slow!

thanks in advance and keep up the good work

**Comment by Yonjuni** [comment]
I guess there is an async task missing at startup ;) https://github.com/SecUSo/privacy-friendly-notes/issues/39
