### ISSUE TITLE
A few suggestion

### ISSUE THREAD

**Issue by sivaraam** [SecUSo/privacy-friendly-notes#42]
I wanted make a few suggestion that would probably improve the app

- [ ] **Manipulating list items** : Allow the user to manipulate the text of the each entry of a list. Currently it is only possible to delete an item by selecting it. It would be better if there was an option to _Edit the item_, _Select the text of that item_.

- [ ] **Ordering Notes** : Allow users to select the sort order of the notes in 2 or more ways (Alphabetical, Creation date, Modified date etc.) and show the notes according to the preference. Currently the app seems to be showing the notes in the order in which it was created which seems to too rigid on the user. The icon that sorts them alphabetically is of little help but would be better if it remembered the preference.

- [ ] **Strike the finished item** : Instead of showing a tick mark on a completed item, showing it using a _Strike over_ the item would be much more appealing.

- [ ] **Swap Export and Share icons** : Swap the location of the _Export_ option and _Share_ option for a note. I guess a user is more likely to share a note than to export a note.

- [ ] **Show _Note updated_ message only when note is updated** : currently the _Note Updated_ message seems to be show each time a user sees a note and comes back to see a list of notes even if he hasn't updated anything. This seems a bit annoying. Show the _Note updated_ message only if th note is really updated (it would be nice if this was done as a check comparing the saved note with the current note for this, instead of a simple flag as this would avoid showing the message for a non-modifying change)

- [ ] **Show notes completely** : Show the contents of the the notes completely when in landscape mode or when the keyboard is active. Currently the content that is being edited is not shown well to the user.  I guess the following screen shots would illustrate what I wanted to convey.
![screenshot_2016-12-17-08-33-05](https://cloud.githubusercontent.com/assets/12448084/21292045/dc3941a2-c51c-11e6-8fc2-5f8d83e82400.png)
![screenshot_2016-12-17-08-34-14](https://cloud.githubusercontent.com/assets/12448084/21292046/e7ebe428-c51c-11e6-9ce4-d375968853d5.png)

**Comment by Yonjuni** [comment]
@sivaraam Thanks for the suggestions, I have sub-divided this issue into a few which will make it easier for us and commented on some that are not in the new issues below. If you wish to follow and discuss your suggestions please use the new issues. 

1. Changing Text list items: https://github.com/SecUSo/privacy-friendly-notes/issues/44
2. Ordering: https://github.com/SecUSo/privacy-friendly-notes/issues/43
3. Striking: https://github.com/SecUSo/privacy-friendly-notes/issues/46
4. Swap Export and Share icons: We currently discuss a overall solution for all Privacy Friendly Apps for sharing and syncing, so this part will be totally redesigned in the future. 
5. Update message: https://github.com/SecUSo/privacy-friendly-notes/issues/45
6. Display of notes: This goes together with https://github.com/SecUSo/privacy-friendly-notes/issues/30 This part will also be redesigned.
