### ISSUE TITLE
Adding of different sorting options.

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-notes#43]
From https://github.com/SecUSo/privacy-friendly-notes/issues/42 "Ordering Notes : Allow users to select the sort order of the notes in 2 or more ways (Alphabetical, Creation date, Modified date etc.) and show the notes according to the preference. Currently the app seems to be showing the notes in the order in which it was created which seems to too rigid on the user. The icon that sorts them alphabetically is of little help but would be better if it remembered the preference."

Note: alphabetical is already included

**Comment by geugen** [comment]
In addition to the previous post: keep the selected sorting order (e.g. after a restart of the app)
