### ISSUE TITLE
focus "Add" input control when opening an existing list

### ISSUE THREAD

**Issue by atomGit** [SecUSo/privacy-friendly-notes#62]
when opening a list, the title edit control is given focus - instead, i think the "Add" edit control should have focus

**Comment by Yonjuni** [comment]
Could you explain this in a little more detail?

**Comment by atomGit** [comment]
when you open a saved list, it is the title of the list that has focus (where the blinking cursor/caret is) - instead, i think it should be the edit control for adding a new list item that has focus (where it says "New item") - this way, if you want to add a new list item, you can just start typing instead of having to focus (tap) the new list item edit control

**Comment by Yonjuni** [comment]
Thanks for explaining ;)

**Comment by atomGit** [comment]
actually i didn't think that out very clearly - even if the "New item" edit control had focus upon opening a saved list, you still have to tap it to get the keyboard to pop up ... hmmm ... still, the list title should probably not have focus when opening a saved list - whatever - totally non-important i guess :)

**Comment by Rdlgrmpf** [comment]
The keyboard is hidden on purpose: https://github.com/SecUSo/privacy-friendly-notes/blob/master/app/src/main/java/org/secuso/privacyfriendlynotes/ChecklistNoteActivity.java#L191

When opening an existing list the user wants to do one of the following:
1. Add an item ->Keyboard should be shown, focus in the input field
2. Check an item -> Keyboard should be hidden so it doesn't take away space and more items are shown

I assumed 2 is more common. Hence, the keyboard is hidden.
