### ISSUE TITLE
Update ETA?

### ISSUE THREAD

**Issue by Sirove** [SecUSo/privacy-friendly-notes#64]
I think this app has the potential to be the most user friendly open source notes app on F-Droid but there are still some already mentioned bugs and missing enhancements that significantly degrade the workflow. 
The last update was in December 2016. Do you have plans to update this app in the near future?

**Comment by Yonjuni** [comment]
@Sirove We plan to update the app in the future, but it is hard to say when. Our apps haven been/are being developed in the framework of SECUSO's programming lab (Usable Security and Privacy Lab at our university).

**Comment by Kamuno** [comment]
Since the question has been answered I will close this issue. Unfortunately we can not give any specific ETA on updates.
