### ISSUE TITLE
Adaptive icon

### ISSUE THREAD

**Issue by mueller-ma** [SecUSo/privacy-friendly-notes#80]
I'd really like to see an adaptive launcher icon for this app. Adaptive icons were introduced in Android 8: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by Kamuno** [comment]
It's on our list and as soon as the next update is released the icon will be added.

**Comment by Kamuno** [comment]
Done via 48d368cb922fda1e7bce6349fc89e71909dcebdc
