### ISSUE TITLE
[Guide] Export and restore your data

### ISSUE THREAD

**Issue by T-vK** [SecUSo/privacy-friendly-notes#94]
Using a Linux computer and two rooted phones, I successfully managed to export my settings and all my data (text notes, audio notes, etc...) and import them on a new device.

Please note: On the phone where you import the data, it will overwrite any existing data for this app, it will not merge your data if you already created notes on that new device.
``` Bash
APP_ID="org.secuso.privacyfriendlynotes"

# Export (RUN WITH OLD PHONE CONNECTED)
sudo adb root
sudo adb pull "/data/data/${APP_ID}"

# Import (RUN WITH NEW PHONE CONNECTED)
sudo adb root
APP_OWNERSHIP=$(sudo adb shell stat --format "%U:%G" "/data/data/${APP_ID}")
sudo adb shell mv "/data/data/${APP_ID}" "/data/data/${APP_ID}_backup"
sudo adb push "./${APP_ID}" "/data/data/${APP_ID}"
sudo adb shell restorecon "/data/data/${APP_ID}"
sudo adb shell chown -R "${APP_OWNERSHIP}" "/data/data/${APP_ID}"
#sudo adb shell rm -rf "/data/data/${APP_ID}_backup"
```

Related: #92 #33 #67 #28

**Comment by licaon-kter** [comment]
Rooted devices are like 0.0001%? Meh

**Comment by T-vK** [comment]
A less reliable (deprecated) method, that micht not require root is adb backup/restore:

Export (RUN WITH OLD PHONE CONNECTED)
```
adb backup -f org.secuso.privacyfriendlynotes.ab -apk
```

Import (RUN WITH NEW PHONE CONNECTED)
```
adb restore org.secuso.privacyfriendlynotes.ab
```

**Comment by belkarx** [comment]
You can also grab the database using `adb backup` as explained in [this](https://android.stackexchange.com/questions/48609/how-can-i-access-the-files-in-data-data-and-copy-them-into-memory-card-withou) SE question
