### ISSUE TITLE
1.1.0 corrupts all notes (wipes all new lines and indentations)

### ISSUE THREAD

**Issue by T-vK** [SecUSo/privacy-friendly-notes#97]
The latest update (installed via Fdroid) corrupted all my text notes.
Every note has been forced into a single line and indentations have been stripped away as well.

**Comment by Kamuno** [comment]
wow... this is really bad... I'm trying to find a way to fix this..

**Comment by Kamuno** [comment]
v1.1.1 should fix the migration.

Sadly if you already opened a note and saved it again there is no way for me to get the original indentation and new lines back because notes are automatically saved when closed. 

I am really sorry. :( :(

Fixed via 83bb4759dd655c2765c172ac3cada1fd8fb33eed

**Comment by Kamuno** [comment]
You can try using the Backup App to save your data. 
https://github.com/SecUSo/privacy-friendly-backup/releases/tag/v1.3
The Backup App is currently in the process of being included in F-Droid.. so the only way to use it currently is install it from GitHub or from the PlayStore.

**Comment by T-vK** [comment]
I have an abd backup fortunately, but I think it's gonna take too much time to merge it with all the notes added since because it doesn't sort by creation date anymore. I think I'll open another issue for that one actually.

Thanks for the quick reaction though. I hope the update will make its way into F-Droid soon so this doesn't happen to too many other people.
