### ISSUE TITLE
Doesn't sort by creation date anymore

### ISSUE THREAD

**Issue by T-vK** [SecUSo/privacy-friendly-notes#98]
My most recently created notes used to be added to the bottom of the list. Since 1.1.0 they are sorted alphabetivally making it almost impossible for me to find my recent notes because I have hundreds and I can't always recall the title I've given. And the search/filter unintuitively doesn't search the titles of the notes.

**Comment by jethrogb** [comment]
I'm experiencing the same issue

**Comment by Kamuno** [comment]
What sorting options would you want apart from creation date?

**Comment by T-vK** [comment]
Here are my thoughts:

I would say 
- Creation Date/Time
- Title
- Last Update Date/Time
- Type

And maybe also Category. But it would probably make more sense to allow sorting while a category is selected (currently, this causes all notes from all categories to show up).

There may also be cases where a user wants to only see notes of a specific type (e.g. audio) sorted by title or creation time or last update time.
To allow for that it might make for sense for "Type" to be a filter, similar to how the Categories work atm. 

So maybe there could be filter options where you can select one or more of:
- Type
- Category

And sort options where you can select one of:
- Title
- Creation Time
- Last Updated Time

And finally it would be cool if that sorted/filtered list could then be fiktered down even more using the search (which should search by title imo and optionally by text-content as well).

**Comment by Kamuno** [comment]
closed in favor of 118.
